-- 全平台历史表和字段中文注释
-- 使用动态 COMMENT，兼容已部署环境和幂等重跑；验证脚本负责阻断漏注释

do $$
declare
    item record;
begin
    for item in
        select * from (values
            ('asset_api', 'WP3 API 资产表'),
            ('asset_business_flow', 'WP3 业务流资产表'),
            ('asset_link', 'WP3 资产追踪关系表'),
            ('asset_page', 'WP3 页面资产表'),
            ('asset_requirement', 'WP3 需求资产表'),
            ('asset_test_case', 'WP3 测试用例资产表'),
            ('asset_test_step', 'WP3 测试步骤表'),
            ('asset_version_history', 'WP3 资产版本历史表'),
            ('audit_log', 'WP1 追加式审计日志表'),
            ('audit_log_archive', 'WP1 审计日志归档表'),
            ('audit_outbox', 'WP1 审计补偿 outbox 表，用于失败审计事件重试'),
            ('base_application', 'WP1 应用主数据表，挂靠项目并保存默认访问地址和敏感策略'),
            ('base_config', 'WP1 平台配置表，支持系统、项目、应用、环境等作用域'),
            ('base_department', 'WP1 部门主数据表，维护组织树和部门状态'),
            ('base_department_manager', 'WP1 部门负责人关系表'),
            ('base_department_member', 'WP1 部门成员关系表'),
            ('base_environment', 'WP1 应用环境表，保存环境入口、健康检查和执行策略'),
            ('base_environment_variable', 'WP1 环境变量表，支持明文、脱敏值和密钥引用'),
            ('base_project', 'WP1 项目主数据表，是资源权限和模型数据出域策略的核心 scope'),
            ('base_project_department', 'WP1 项目与部门关系表'),
            ('base_project_member', 'WP1 项目成员关系表'),
            ('document_input_candidate', 'WP4 文档解析出的候选需求表'),
            ('document_input_field_mapping', 'WP4 文档字段映射配置表'),
            ('document_input_import', 'WP4 文档导入任务表'),
            ('document_input_parse_feedback_sample', 'WP4 解析反馈样本表'),
            ('document_input_retention_archive', 'WP4 文档输入留存归档表'),
            ('document_input_source', 'WP4 文档输入源配置表'),
            ('document_input_webhook_event', 'WP4 Webhook 事件接收与重放表'),
            ('iam_session', 'WP1 用户会话表，保存访问令牌和刷新令牌摘要'),
            ('iam_user', 'WP1 用户身份表，保存登录账号和认证状态'),
            ('ma_invocation_job', 'WP2 异步模型调用任务表'),
            ('ma_invocation_log', 'WP2 模型调用审计日志表'),
            ('ma_model_provider', 'WP2 模型供应商配置表'),
            ('ma_prompt_template', 'WP2 Prompt 模板版本表'),
            ('rbac_permission', 'WP1 权限定义表'),
            ('rbac_role', 'WP1 角色定义表'),
            ('rbac_role_binding', 'WP1 角色绑定表，记录用户、项目或应用等主体的授权关系'),
            ('rbac_role_permission', 'WP1 角色权限关系表'),
            ('secret_local_store', 'WP1 本地加密密钥值表，只保存密文、IV 和认证标签'),
            ('secret_provider', 'WP1 密钥供应商配置表，只保存非敏感配置元数据'),
            ('secret_reference', 'WP1 密钥引用表，保存密钥定位、用途和脱敏展示信息'),
            ('test_design_candidate', 'WP5 候选测试用例表'),
            ('test_design_publish_record', 'WP5 候选发布记录表'),
            ('test_design_review_record', 'WP5 候选评审审计表'),
            ('test_design_task', 'WP5 AI 用例生成任务表')
        ) as comments(table_name, description)
    loop
        if exists (
            select 1 from information_schema.tables
            where table_schema = current_schema() and table_name = item.table_name and table_type = 'BASE TABLE'
        ) then
            execute format('comment on table %I is %L', item.table_name, item.description);
        end if;
    end loop;
end $$;

do $$
declare
    item record;
begin
    for item in
        select * from (values
            ('asset_api', 'id', '主键 ID'),
            ('asset_api', 'project_id', '所属项目 ID，用于权限 scope、筛选和数据隔离'),
            ('asset_api', 'code', '业务编码'),
            ('asset_api', 'service_name', '服务名称'),
            ('asset_api', 'path', '树路径或接口路径'),
            ('asset_api', 'http_method', 'HTTP 方法'),
            ('asset_api', 'summary', '摘要'),
            ('asset_api', 'description', '业务说明'),
            ('asset_api', 'source', '来源类型'),
            ('asset_api', 'source_ref', '外部来源引用'),
            ('asset_api', 'version', '版本号或乐观锁版本'),
            ('asset_api', 'request_schema', '请求结构定义 JSON'),
            ('asset_api', 'response_schema', '响应结构定义 JSON'),
            ('asset_api', 'status', '业务状态'),
            ('asset_api', 'tags', '标签'),
            ('asset_api', 'created_by', '创建人'),
            ('asset_api', 'created_at', '创建时间'),
            ('asset_api', 'updated_by', '更新人'),
            ('asset_api', 'updated_at', '最近更新时间'),
            ('asset_api', 'deleted_by', '删除人'),
            ('asset_api', 'deleted_at', '删除时间'),
            ('asset_api', 'lifecycle_status', '资产生命周期状态'),
            ('asset_api', 'archived_by', '归档人'),
            ('asset_api', 'archived_at', '归档时间'),
            ('asset_business_flow', 'id', '主键 ID'),
            ('asset_business_flow', 'project_id', '所属项目 ID，用于权限 scope、筛选和数据隔离'),
            ('asset_business_flow', 'code', '业务编码'),
            ('asset_business_flow', 'name', '名称'),
            ('asset_business_flow', 'description', '业务说明'),
            ('asset_business_flow', 'flow_json', '业务流程 JSON'),
            ('asset_business_flow', 'priority', '优先级'),
            ('asset_business_flow', 'status', '业务状态'),
            ('asset_business_flow', 'created_by', '创建人'),
            ('asset_business_flow', 'created_at', '创建时间'),
            ('asset_business_flow', 'updated_by', '更新人'),
            ('asset_business_flow', 'updated_at', '最近更新时间'),
            ('asset_business_flow', 'deleted_by', '删除人'),
            ('asset_business_flow', 'deleted_at', '删除时间'),
            ('asset_business_flow', 'version', '版本号或乐观锁版本'),
            ('asset_business_flow', 'lifecycle_status', '资产生命周期状态'),
            ('asset_business_flow', 'archived_by', '归档人'),
            ('asset_business_flow', 'archived_at', '归档时间'),
            ('asset_link', 'id', '主键 ID'),
            ('asset_link', 'source_type', '来源资产类型'),
            ('asset_link', 'source_id', '来源资产 ID'),
            ('asset_link', 'target_type', '目标资产类型'),
            ('asset_link', 'target_id', '目标资产 ID'),
            ('asset_link', 'link_type', '关系类型'),
            ('asset_link', 'created_by', '创建人'),
            ('asset_link', 'created_at', '创建时间'),
            ('asset_link', 'deleted_at', '删除时间'),
            ('asset_page', 'id', '主键 ID'),
            ('asset_page', 'project_id', '所属项目 ID，用于权限 scope、筛选和数据隔离'),
            ('asset_page', 'code', '业务编码'),
            ('asset_page', 'name', '名称'),
            ('asset_page', 'url_pattern', 'URL 匹配规则'),
            ('asset_page', 'source', '来源类型'),
            ('asset_page', 'source_ref', '外部来源引用'),
            ('asset_page', 'component_tree', '页面组件树 JSON'),
            ('asset_page', 'screenshot_url', '页面截图地址'),
            ('asset_page', 'status', '业务状态'),
            ('asset_page', 'created_by', '创建人'),
            ('asset_page', 'created_at', '创建时间'),
            ('asset_page', 'updated_by', '更新人'),
            ('asset_page', 'updated_at', '最近更新时间'),
            ('asset_page', 'deleted_by', '删除人'),
            ('asset_page', 'deleted_at', '删除时间'),
            ('asset_page', 'version', '版本号或乐观锁版本'),
            ('asset_page', 'lifecycle_status', '资产生命周期状态'),
            ('asset_page', 'archived_by', '归档人'),
            ('asset_page', 'archived_at', '归档时间'),
            ('asset_page', 'source_version', '来源版本'),
            ('asset_requirement', 'id', '主键 ID'),
            ('asset_requirement', 'project_id', '所属项目 ID，用于权限 scope、筛选和数据隔离'),
            ('asset_requirement', 'code', '业务编码'),
            ('asset_requirement', 'title', '标题'),
            ('asset_requirement', 'description', '业务说明'),
            ('asset_requirement', 'source', '来源类型'),
            ('asset_requirement', 'source_ref', '外部来源引用'),
            ('asset_requirement', 'source_url', '外部来源地址'),
            ('asset_requirement', 'priority', '优先级'),
            ('asset_requirement', 'status', '业务状态'),
            ('asset_requirement', 'version', '版本号或乐观锁版本'),
            ('asset_requirement', 'acceptance_criteria', '验收标准'),
            ('asset_requirement', 'business_rules', '业务规则'),
            ('asset_requirement', 'tags', '标签'),
            ('asset_requirement', 'created_by', '创建人'),
            ('asset_requirement', 'created_at', '创建时间'),
            ('asset_requirement', 'updated_by', '更新人'),
            ('asset_requirement', 'updated_at', '最近更新时间'),
            ('asset_requirement', 'deleted_by', '删除人'),
            ('asset_requirement', 'deleted_at', '删除时间'),
            ('asset_requirement', 'lifecycle_status', '资产生命周期状态'),
            ('asset_requirement', 'archived_by', '归档人'),
            ('asset_requirement', 'archived_at', '归档时间'),
            ('asset_test_case', 'id', '主键 ID'),
            ('asset_test_case', 'project_id', '所属项目 ID，用于权限 scope、筛选和数据隔离'),
            ('asset_test_case', 'code', '业务编码'),
            ('asset_test_case', 'title', '标题'),
            ('asset_test_case', 'description', '业务说明'),
            ('asset_test_case', 'case_type', '用例类型'),
            ('asset_test_case', 'priority', '优先级'),
            ('asset_test_case', 'status', '业务状态'),
            ('asset_test_case', 'preconditions', '前置条件'),
            ('asset_test_case', 'test_data_ref', '测试数据引用'),
            ('asset_test_case', 'automation_status', '自动化状态'),
            ('asset_test_case', 'version', '版本号或乐观锁版本'),
            ('asset_test_case', 'source', '来源类型'),
            ('asset_test_case', 'source_ref', '外部来源引用'),
            ('asset_test_case', 'tags', '标签'),
            ('asset_test_case', 'created_by', '创建人'),
            ('asset_test_case', 'created_at', '创建时间'),
            ('asset_test_case', 'updated_by', '更新人'),
            ('asset_test_case', 'updated_at', '最近更新时间'),
            ('asset_test_case', 'deleted_by', '删除人'),
            ('asset_test_case', 'deleted_at', '删除时间'),
            ('asset_test_case', 'lifecycle_status', '资产生命周期状态'),
            ('asset_test_case', 'archived_by', '归档人'),
            ('asset_test_case', 'archived_at', '归档时间'),
            ('asset_test_step', 'id', '主键 ID'),
            ('asset_test_step', 'case_id', '测试用例 ID'),
            ('asset_test_step', 'step_order', '步骤序号'),
            ('asset_test_step', 'action', '操作动作'),
            ('asset_test_step', 'target', '操作目标'),
            ('asset_test_step', 'input_data', '输入数据'),
            ('asset_test_step', 'expected_result', '预期结果'),
            ('asset_test_step', 'data_ref', '数据引用'),
            ('asset_test_step', 'created_by', '创建人'),
            ('asset_test_step', 'created_at', '创建时间'),
            ('asset_test_step', 'updated_by', '更新人'),
            ('asset_test_step', 'updated_at', '最近更新时间'),
            ('asset_version_history', 'id', '主键 ID'),
            ('asset_version_history', 'project_id', '所属项目 ID，用于权限 scope、筛选和数据隔离'),
            ('asset_version_history', 'asset_type', '资产类型'),
            ('asset_version_history', 'asset_id', '资产 ID'),
            ('asset_version_history', 'version', '版本号或乐观锁版本'),
            ('asset_version_history', 'change_type', '变更类型'),
            ('asset_version_history', 'actor', '操作人'),
            ('asset_version_history', 'changed_fields', '变更字段列表'),
            ('asset_version_history', 'diff_json', '字段差异 JSON'),
            ('asset_version_history', 'snapshot_json', '快照 JSON'),
            ('asset_version_history', 'trace_id', '链路追踪 ID'),
            ('asset_version_history', 'created_at', '创建时间'),
            ('audit_log', 'id', '主键 ID'),
            ('audit_log', 'trace_id', '链路追踪 ID'),
            ('audit_log', 'idempotency_key', '幂等键'),
            ('audit_log', 'actor_type', '操作主体类型'),
            ('audit_log', 'actor_user_id', '操作用户 ID'),
            ('audit_log', 'actor_service', '操作服务标识'),
            ('audit_log', 'actor_ip', '操作来源 IP'),
            ('audit_log', 'user_agent', '用户代理'),
            ('audit_log', 'action', '操作动作'),
            ('audit_log', 'resource_type', '资源类型'),
            ('audit_log', 'resource_id', '资源 ID'),
            ('audit_log', 'scope_type', '作用域类型'),
            ('audit_log', 'scope_id', '作用域 ID'),
            ('audit_log', 'result', '处理结果'),
            ('audit_log', 'before_json', '操作前快照 JSON'),
            ('audit_log', 'after_json', '操作后快照 JSON'),
            ('audit_log', 'diff_json', '字段差异 JSON'),
            ('audit_log', 'reason', '原因说明'),
            ('audit_log', 'created_at', '创建时间'),
            ('audit_log_archive', 'id', '归档审计日志字段：主键 ID'),
            ('audit_log_archive', 'trace_id', '归档审计日志字段：链路追踪 ID'),
            ('audit_log_archive', 'idempotency_key', '归档审计日志字段：幂等键'),
            ('audit_log_archive', 'actor_type', '归档审计日志字段：操作主体类型'),
            ('audit_log_archive', 'actor_user_id', '归档审计日志字段：操作用户 ID'),
            ('audit_log_archive', 'actor_service', '归档审计日志字段：操作服务标识'),
            ('audit_log_archive', 'actor_ip', '归档审计日志字段：操作来源 IP'),
            ('audit_log_archive', 'user_agent', '归档审计日志字段：用户代理'),
            ('audit_log_archive', 'action', '归档审计日志字段：操作动作'),
            ('audit_log_archive', 'resource_type', '归档审计日志字段：资源类型'),
            ('audit_log_archive', 'resource_id', '归档审计日志字段：资源 ID'),
            ('audit_log_archive', 'scope_type', '归档审计日志字段：作用域类型'),
            ('audit_log_archive', 'scope_id', '归档审计日志字段：作用域 ID'),
            ('audit_log_archive', 'result', '归档审计日志字段：处理结果'),
            ('audit_log_archive', 'before_json', '归档审计日志字段：操作前快照 JSON'),
            ('audit_log_archive', 'after_json', '归档审计日志字段：操作后快照 JSON'),
            ('audit_log_archive', 'diff_json', '归档审计日志字段：字段差异 JSON'),
            ('audit_log_archive', 'reason', '归档审计日志字段：原因说明'),
            ('audit_log_archive', 'created_at', '归档审计日志字段：创建时间'),
            ('audit_log_archive', 'archived_at', '归档时间'),
            ('audit_outbox', 'id', '主键 ID'),
            ('audit_outbox', 'idempotency_key', '幂等键'),
            ('audit_outbox', 'event_payload_json', '审计事件载荷 JSON'),
            ('audit_outbox', 'status', '业务状态'),
            ('audit_outbox', 'retry_count', '重试次数'),
            ('audit_outbox', 'next_retry_at', '下次重试时间'),
            ('audit_outbox', 'last_error', '最近错误摘要'),
            ('audit_outbox', 'locked_at', '锁定时间'),
            ('audit_outbox', 'locked_by', '锁定执行者'),
            ('audit_outbox', 'created_at', '创建时间'),
            ('audit_outbox', 'updated_at', '最近更新时间'),
            ('base_application', 'id', '主键 ID'),
            ('base_application', 'project_id', '所属项目 ID，用于权限 scope、筛选和数据隔离'),
            ('base_application', 'code', '业务编码'),
            ('base_application', 'name', '名称'),
            ('base_application', 'app_type', '应用类型'),
            ('base_application', 'default_web_url', '默认 Web 地址'),
            ('base_application', 'default_api_base_url', '默认 API 基础地址'),
            ('base_application', 'repo_url', '代码仓库地址'),
            ('base_application', 'service_identifier', '服务标识'),
            ('base_application', 'sensitivity_level', '敏感级别'),
            ('base_application', 'allow_public_model', '是否允许公网模型处理该范围数据'),
            ('base_application', 'status', '业务状态'),
            ('base_application', 'description', '业务说明'),
            ('base_application', 'created_by', '创建人'),
            ('base_application', 'created_at', '创建时间'),
            ('base_application', 'updated_by', '更新人'),
            ('base_application', 'updated_at', '最近更新时间'),
            ('base_application', 'deleted_by', '删除人'),
            ('base_application', 'deleted_at', '删除时间'),
            ('base_application', 'version', '版本号或乐观锁版本'),
            ('base_config', 'id', '主键 ID'),
            ('base_config', 'scope_type', '作用域类型'),
            ('base_config', 'scope_id', '作用域 ID'),
            ('base_config', 'config_key', '配置键'),
            ('base_config', 'value_kind', '配置值类型'),
            ('base_config', 'value_json', '配置值 JSON'),
            ('base_config', 'secret_ref', '密钥引用'),
            ('base_config', 'masked_value', '脱敏展示值'),
            ('base_config', 'status', '业务状态'),
            ('base_config', 'created_by', '创建人'),
            ('base_config', 'created_at', '创建时间'),
            ('base_config', 'updated_by', '更新人'),
            ('base_config', 'updated_at', '最近更新时间'),
            ('base_config', 'deleted_by', '删除人'),
            ('base_config', 'deleted_at', '删除时间'),
            ('base_config', 'version', '版本号或乐观锁版本'),
            ('base_department', 'id', '主键 ID'),
            ('base_department', 'parent_id', '父级部门 ID'),
            ('base_department', 'code', '业务编码'),
            ('base_department', 'name', '名称'),
            ('base_department', 'path', '树路径或接口路径'),
            ('base_department', 'level', '层级'),
            ('base_department', 'sort_order', '排序值'),
            ('base_department', 'status', '业务状态'),
            ('base_department', 'created_by', '创建人'),
            ('base_department', 'created_at', '创建时间'),
            ('base_department', 'updated_by', '更新人'),
            ('base_department', 'updated_at', '最近更新时间'),
            ('base_department', 'deleted_by', '删除人'),
            ('base_department', 'deleted_at', '删除时间'),
            ('base_department', 'version', '版本号或乐观锁版本'),
            ('base_department_manager', 'id', '主键 ID'),
            ('base_department_manager', 'dept_id', '所属部门 ID'),
            ('base_department_manager', 'user_id', '用户 ID'),
            ('base_department_manager', 'status', '业务状态'),
            ('base_department_manager', 'created_by', '创建人'),
            ('base_department_manager', 'created_at', '创建时间'),
            ('base_department_manager', 'updated_by', '更新人'),
            ('base_department_manager', 'updated_at', '最近更新时间'),
            ('base_department_manager', 'deleted_by', '删除人'),
            ('base_department_manager', 'deleted_at', '删除时间'),
            ('base_department_manager', 'version', '版本号或乐观锁版本'),
            ('base_department_member', 'id', '主键 ID'),
            ('base_department_member', 'dept_id', '所属部门 ID'),
            ('base_department_member', 'user_id', '用户 ID'),
            ('base_department_member', 'is_primary', '是否主关系'),
            ('base_department_member', 'position', '岗位'),
            ('base_department_member', 'status', '业务状态'),
            ('base_department_member', 'created_by', '创建人'),
            ('base_department_member', 'created_at', '创建时间'),
            ('base_department_member', 'updated_by', '更新人'),
            ('base_department_member', 'updated_at', '最近更新时间'),
            ('base_department_member', 'deleted_by', '删除人'),
            ('base_department_member', 'deleted_at', '删除时间'),
            ('base_department_member', 'version', '版本号或乐观锁版本'),
            ('base_environment', 'id', '主键 ID'),
            ('base_environment', 'project_id', '所属项目 ID，用于权限 scope、筛选和数据隔离'),
            ('base_environment', 'app_id', '所属应用 ID'),
            ('base_environment', 'scope_type', '作用域类型'),
            ('base_environment', 'code', '业务编码'),
            ('base_environment', 'name', '名称'),
            ('base_environment', 'env_type', '环境类型'),
            ('base_environment', 'web_url', 'Web 访问地址'),
            ('base_environment', 'api_base_url', 'API 基础地址'),
            ('base_environment', 'execution_policy_json', '执行策略 JSON'),
            ('base_environment', 'health_check_json', '健康检查配置 JSON'),
            ('base_environment', 'auth_secret_ref', '环境认证密钥引用'),
            ('base_environment', 'status', '业务状态'),
            ('base_environment', 'created_by', '创建人'),
            ('base_environment', 'created_at', '创建时间'),
            ('base_environment', 'updated_by', '更新人'),
            ('base_environment', 'updated_at', '最近更新时间'),
            ('base_environment', 'deleted_by', '删除人'),
            ('base_environment', 'deleted_at', '删除时间'),
            ('base_environment', 'version', '版本号或乐观锁版本'),
            ('base_environment_variable', 'id', '主键 ID'),
            ('base_environment_variable', 'env_id', '所属环境 ID'),
            ('base_environment_variable', 'key', '变量键'),
            ('base_environment_variable', 'value_kind', '配置值类型'),
            ('base_environment_variable', 'plain_value', '明文配置值'),
            ('base_environment_variable', 'secret_ref', '密钥引用'),
            ('base_environment_variable', 'secret_provider', '密钥供应商'),
            ('base_environment_variable', 'secret_version', '密钥版本'),
            ('base_environment_variable', 'masked_value', '脱敏展示值'),
            ('base_environment_variable', 'description', '业务说明'),
            ('base_environment_variable', 'status', '业务状态'),
            ('base_environment_variable', 'created_by', '创建人'),
            ('base_environment_variable', 'created_at', '创建时间'),
            ('base_environment_variable', 'updated_by', '更新人'),
            ('base_environment_variable', 'updated_at', '最近更新时间'),
            ('base_environment_variable', 'deleted_by', '删除人'),
            ('base_environment_variable', 'deleted_at', '删除时间'),
            ('base_environment_variable', 'version', '版本号或乐观锁版本'),
            ('base_project', 'id', '主键 ID'),
            ('base_project', 'code', '业务编码'),
            ('base_project', 'name', '名称'),
            ('base_project', 'status', '业务状态'),
            ('base_project', 'sensitivity_level', '敏感级别'),
            ('base_project', 'allow_public_model', '是否允许公网模型处理该范围数据'),
            ('base_project', 'default_resource_pool', '默认资源池'),
            ('base_project', 'description', '业务说明'),
            ('base_project', 'created_by', '创建人'),
            ('base_project', 'created_at', '创建时间'),
            ('base_project', 'updated_by', '更新人'),
            ('base_project', 'updated_at', '最近更新时间'),
            ('base_project', 'deleted_by', '删除人'),
            ('base_project', 'deleted_at', '删除时间'),
            ('base_project', 'version', '版本号或乐观锁版本'),
            ('base_project_department', 'id', '主键 ID'),
            ('base_project_department', 'project_id', '所属项目 ID，用于权限 scope、筛选和数据隔离'),
            ('base_project_department', 'dept_id', '所属部门 ID'),
            ('base_project_department', 'relation_type', '关系类型'),
            ('base_project_department', 'is_primary', '是否主关系'),
            ('base_project_department', 'status', '业务状态'),
            ('base_project_department', 'created_by', '创建人'),
            ('base_project_department', 'created_at', '创建时间'),
            ('base_project_department', 'updated_by', '更新人'),
            ('base_project_department', 'updated_at', '最近更新时间'),
            ('base_project_department', 'deleted_by', '删除人'),
            ('base_project_department', 'deleted_at', '删除时间'),
            ('base_project_department', 'version', '版本号或乐观锁版本'),
            ('base_project_member', 'id', '主键 ID'),
            ('base_project_member', 'project_id', '所属项目 ID，用于权限 scope、筛选和数据隔离'),
            ('base_project_member', 'user_id', '用户 ID'),
            ('base_project_member', 'member_type', '成员类型'),
            ('base_project_member', 'status', '业务状态'),
            ('base_project_member', 'joined_at', '加入时间'),
            ('base_project_member', 'created_by', '创建人'),
            ('base_project_member', 'created_at', '创建时间'),
            ('base_project_member', 'updated_by', '更新人'),
            ('base_project_member', 'updated_at', '最近更新时间'),
            ('base_project_member', 'deleted_by', '删除人'),
            ('base_project_member', 'deleted_at', '删除时间'),
            ('base_project_member', 'version', '版本号或乐观锁版本'),
            ('document_input_candidate', 'id', '主键 ID'),
            ('document_input_candidate', 'import_id', '文档导入任务 ID'),
            ('document_input_candidate', 'project_id', '所属项目 ID，用于权限 scope、筛选和数据隔离'),
            ('document_input_candidate', 'title', '标题'),
            ('document_input_candidate', 'description', '业务说明'),
            ('document_input_candidate', 'priority', '优先级'),
            ('document_input_candidate', 'acceptance_criteria', '验收标准'),
            ('document_input_candidate', 'tags', '标签'),
            ('document_input_candidate', 'status', '业务状态'),
            ('document_input_candidate', 'source_ref', '外部来源引用'),
            ('document_input_candidate', 'source_fragment', '来源片段'),
            ('document_input_candidate', 'external_requirement_id', '外部需求 ID'),
            ('document_input_candidate', 'confidence', '置信度'),
            ('document_input_candidate', 'parse_source', '解析来源'),
            ('document_input_candidate', 'model_invocation_id', '模型调用记录 ID'),
            ('document_input_candidate', 'model_provider_name', '模型供应商名称'),
            ('document_input_candidate', 'model_name', '模型名称'),
            ('document_input_candidate', 'asset_requirement_id', '需求资产 ID'),
            ('document_input_candidate', 'error_message', '错误摘要'),
            ('document_input_candidate', 'ignored_reason', '忽略原因'),
            ('document_input_candidate', 'confirmed_by', '确认人'),
            ('document_input_candidate', 'confirmed_at', '确认时间'),
            ('document_input_candidate', 'created_by', '创建人'),
            ('document_input_candidate', 'created_at', '创建时间'),
            ('document_input_candidate', 'updated_by', '更新人'),
            ('document_input_candidate', 'updated_at', '最近更新时间'),
            ('document_input_candidate', 'deleted_by', '删除人'),
            ('document_input_candidate', 'deleted_at', '删除时间'),
            ('document_input_candidate', 'version', '版本号或乐观锁版本'),
            ('document_input_field_mapping', 'id', '主键 ID'),
            ('document_input_field_mapping', 'mapping_code', '字段映射编码'),
            ('document_input_field_mapping', 'name', '名称'),
            ('document_input_field_mapping', 'item_path', '条目路径'),
            ('document_input_field_mapping', 'title_path', '标题字段路径'),
            ('document_input_field_mapping', 'description_path', '描述字段路径'),
            ('document_input_field_mapping', 'priority_path', '优先级字段路径'),
            ('document_input_field_mapping', 'acceptance_criteria_path', '验收标准字段路径'),
            ('document_input_field_mapping', 'tags_path', '标签字段路径'),
            ('document_input_field_mapping', 'created_by', '创建人'),
            ('document_input_field_mapping', 'created_at', '创建时间'),
            ('document_input_field_mapping', 'updated_by', '更新人'),
            ('document_input_field_mapping', 'updated_at', '最近更新时间'),
            ('document_input_field_mapping', 'deleted_by', '删除人'),
            ('document_input_field_mapping', 'deleted_at', '删除时间'),
            ('document_input_field_mapping', 'version', '版本号或乐观锁版本'),
            ('document_input_import', 'id', '主键 ID'),
            ('document_input_import', 'project_id', '所属项目 ID，用于权限 scope、筛选和数据隔离'),
            ('document_input_import', 'source_id', '来源资产 ID'),
            ('document_input_import', 'source_code', '文档输入源编码'),
            ('document_input_import', 'source_type', '来源资产类型'),
            ('document_input_import', 'source_ref', '外部来源引用'),
            ('document_input_import', 'source_url', '外部来源地址'),
            ('document_input_import', 'title', '标题'),
            ('document_input_import', 'status', '业务状态'),
            ('document_input_import', 'total_parsed', '解析总数'),
            ('document_input_import', 'total_created', '创建总数'),
            ('document_input_import', 'created_requirement_ids', '已创建需求 ID 列表'),
            ('document_input_import', 'error_message', '错误摘要'),
            ('document_input_import', 'raw_digest', '原始内容摘要'),
            ('document_input_import', 'created_by', '创建人'),
            ('document_input_import', 'created_at', '创建时间'),
            ('document_input_import', 'updated_by', '更新人'),
            ('document_input_import', 'updated_at', '最近更新时间'),
            ('document_input_import', 'deleted_by', '删除人'),
            ('document_input_import', 'deleted_at', '删除时间'),
            ('document_input_import', 'version', '版本号或乐观锁版本'),
            ('document_input_parse_feedback_sample', 'id', '主键 ID'),
            ('document_input_parse_feedback_sample', 'candidate_id', '候选 ID'),
            ('document_input_parse_feedback_sample', 'import_id', '文档导入任务 ID'),
            ('document_input_parse_feedback_sample', 'project_id', '所属项目 ID，用于权限 scope、筛选和数据隔离'),
            ('document_input_parse_feedback_sample', 'source_type', '来源资产类型'),
            ('document_input_parse_feedback_sample', 'input_digest', '输入摘要'),
            ('document_input_parse_feedback_sample', 'source_ref_digest', '来源引用摘要'),
            ('document_input_parse_feedback_sample', 'source_fragment_digest', '来源片段摘要'),
            ('document_input_parse_feedback_sample', 'parse_source', '解析来源'),
            ('document_input_parse_feedback_sample', 'model_invocation_id', '模型调用记录 ID'),
            ('document_input_parse_feedback_sample', 'model_provider_name', '模型供应商名称'),
            ('document_input_parse_feedback_sample', 'model_name', '模型名称'),
            ('document_input_parse_feedback_sample', 'correction_type', '修正类型'),
            ('document_input_parse_feedback_sample', 'changed_fields', '变更字段列表'),
            ('document_input_parse_feedback_sample', 'before_snapshot_json', '修正前快照 JSON'),
            ('document_input_parse_feedback_sample', 'after_snapshot_json', '修正后快照 JSON'),
            ('document_input_parse_feedback_sample', 'curation_status', '样本治理状态'),
            ('document_input_parse_feedback_sample', 'created_by', '创建人'),
            ('document_input_parse_feedback_sample', 'created_at', '创建时间'),
            ('document_input_parse_feedback_sample', 'updated_by', '更新人'),
            ('document_input_parse_feedback_sample', 'updated_at', '最近更新时间'),
            ('document_input_parse_feedback_sample', 'deleted_by', '删除人'),
            ('document_input_parse_feedback_sample', 'deleted_at', '删除时间'),
            ('document_input_parse_feedback_sample', 'version', '版本号或乐观锁版本'),
            ('document_input_retention_archive', 'id', '主键 ID'),
            ('document_input_retention_archive', 'record_type', '归档记录类型'),
            ('document_input_retention_archive', 'record_id', '归档记录 ID'),
            ('document_input_retention_archive', 'project_id', '所属项目 ID，用于权限 scope、筛选和数据隔离'),
            ('document_input_retention_archive', 'source_code', '文档输入源编码'),
            ('document_input_retention_archive', 'payload_digest', '载荷摘要'),
            ('document_input_retention_archive', 'original_created_at', '原记录创建时间'),
            ('document_input_retention_archive', 'snapshot_json', '快照 JSON'),
            ('document_input_retention_archive', 'archived_at', '归档时间'),
            ('document_input_source', 'id', '主键 ID'),
            ('document_input_source', 'source_code', '文档输入源编码'),
            ('document_input_source', 'name', '名称'),
            ('document_input_source', 'source_type', '来源资产类型'),
            ('document_input_source', 'status', '业务状态'),
            ('document_input_source', 'endpoint_url', '数据源端点 URL'),
            ('document_input_source', 'default_project_id', '默认项目 ID'),
            ('document_input_source', 'mapping_id', '字段映射 ID'),
            ('document_input_source', 'secret_ref', '密钥引用'),
            ('document_input_source', 'event_version', '事件协议版本'),
            ('document_input_source', 'mapping_version', '映射版本'),
            ('document_input_source', 'description', '业务说明'),
            ('document_input_source', 'created_by', '创建人'),
            ('document_input_source', 'created_at', '创建时间'),
            ('document_input_source', 'updated_by', '更新人'),
            ('document_input_source', 'updated_at', '最近更新时间'),
            ('document_input_source', 'deleted_by', '删除人'),
            ('document_input_source', 'deleted_at', '删除时间'),
            ('document_input_source', 'version', '版本号或乐观锁版本'),
            ('document_input_webhook_event', 'id', '主键 ID'),
            ('document_input_webhook_event', 'source_id', '来源资产 ID'),
            ('document_input_webhook_event', 'import_id', '文档导入任务 ID'),
            ('document_input_webhook_event', 'source_code', '文档输入源编码'),
            ('document_input_webhook_event', 'event_id', '外部事件 ID'),
            ('document_input_webhook_event', 'idempotency_key', '幂等键'),
            ('document_input_webhook_event', 'event_type', '事件类型'),
            ('document_input_webhook_event', 'event_version', '事件协议版本'),
            ('document_input_webhook_event', 'signature_status', '签名校验状态'),
            ('document_input_webhook_event', 'status', '业务状态'),
            ('document_input_webhook_event', 'payload_digest', '载荷摘要'),
            ('document_input_webhook_event', 'raw_payload', '原始事件载荷'),
            ('document_input_webhook_event', 'error_message', '错误摘要'),
            ('document_input_webhook_event', 'retry_count', '重试次数'),
            ('document_input_webhook_event', 'replay_by', '重放人'),
            ('document_input_webhook_event', 'replay_at', '重放时间'),
            ('document_input_webhook_event', 'replay_trace_id', '重放链路追踪 ID'),
            ('document_input_webhook_event', 'received_at', '接收时间'),
            ('document_input_webhook_event', 'processed_at', '处理时间'),
            ('document_input_webhook_event', 'created_by', '创建人'),
            ('document_input_webhook_event', 'created_at', '创建时间'),
            ('document_input_webhook_event', 'updated_by', '更新人'),
            ('document_input_webhook_event', 'updated_at', '最近更新时间'),
            ('document_input_webhook_event', 'deleted_by', '删除人'),
            ('document_input_webhook_event', 'deleted_at', '删除时间'),
            ('document_input_webhook_event', 'version', '版本号或乐观锁版本'),
            ('iam_session', 'id', '主键 ID'),
            ('iam_session', 'user_id', '用户 ID'),
            ('iam_session', 'session_token_hash', '会话令牌哈希'),
            ('iam_session', 'refresh_token_hash', '刷新令牌哈希'),
            ('iam_session', 'auth_version', '认证版本号，用于批量失效会话'),
            ('iam_session', 'client_ip', '客户端 IP'),
            ('iam_session', 'user_agent', '用户代理'),
            ('iam_session', 'expires_at', '过期时间'),
            ('iam_session', 'refreshed_at', '刷新时间'),
            ('iam_session', 'revoked_at', '撤销时间'),
            ('iam_session', 'revoked_by', '撤销人'),
            ('iam_session', 'revoke_reason', '撤销原因'),
            ('iam_session', 'created_at', '创建时间'),
            ('iam_user', 'id', '主键 ID'),
            ('iam_user', 'username', '用户名'),
            ('iam_user', 'password_hash', '密码哈希'),
            ('iam_user', 'display_name', '显示名'),
            ('iam_user', 'email', '邮箱'),
            ('iam_user', 'mobile', '手机号'),
            ('iam_user', 'status', '业务状态'),
            ('iam_user', 'external_id', '外部身份 ID'),
            ('iam_user', 'auth_version', '认证版本号，用于批量失效会话'),
            ('iam_user', 'must_change_password', '是否必须修改密码'),
            ('iam_user', 'last_login_at', '最近登录时间'),
            ('iam_user', 'created_by', '创建人'),
            ('iam_user', 'created_at', '创建时间'),
            ('iam_user', 'updated_by', '更新人'),
            ('iam_user', 'updated_at', '最近更新时间'),
            ('iam_user', 'deleted_by', '删除人'),
            ('iam_user', 'deleted_at', '删除时间'),
            ('iam_user', 'version', '版本号或乐观锁版本'),
            ('ma_invocation_job', 'job_id', '异步任务 ID'),
            ('ma_invocation_job', 'status', '业务状态'),
            ('ma_invocation_job', 'request_json', '请求 JSON，禁止包含密钥明文'),
            ('ma_invocation_job', 'actor_service', '操作服务标识'),
            ('ma_invocation_job', 'delegated_user_id', '代理用户 ID'),
            ('ma_invocation_job', 'trace_id', '链路追踪 ID'),
            ('ma_invocation_job', 'created_at', '创建时间'),
            ('ma_invocation_job', 'started_at', '开始时间'),
            ('ma_invocation_job', 'finished_at', '结束时间'),
            ('ma_invocation_job', 'invocation_id', '模型调用记录 ID'),
            ('ma_invocation_job', 'error_code', '错误编码'),
            ('ma_invocation_job', 'error_message', '错误摘要'),
            ('ma_invocation_job', 'response_json', '响应 JSON'),
            ('ma_invocation_job', 'updated_at', '最近更新时间'),
            ('ma_invocation_job', 'version', '版本号或乐观锁版本'),
            ('ma_invocation_log', 'id', '主键 ID'),
            ('ma_invocation_log', 'project_id', '所属项目 ID，用于权限 scope、筛选和数据隔离'),
            ('ma_invocation_log', 'application_id', '所属应用 ID'),
            ('ma_invocation_log', 'environment_id', '所属环境 ID'),
            ('ma_invocation_log', 'prompt_key', 'Prompt 模板标识'),
            ('ma_invocation_log', 'prompt_version', 'Prompt 模板版本'),
            ('ma_invocation_log', 'provider_id', '供应商 ID'),
            ('ma_invocation_log', 'provider_name', '供应商名称'),
            ('ma_invocation_log', 'model_name', '模型名称'),
            ('ma_invocation_log', 'status', '业务状态'),
            ('ma_invocation_log', 'fallback_used', '是否使用 fallback'),
            ('ma_invocation_log', 'prompt_digest', 'Prompt 摘要'),
            ('ma_invocation_log', 'request_preview', '请求预览，必须脱敏截断'),
            ('ma_invocation_log', 'response_preview', '响应预览，必须脱敏截断'),
            ('ma_invocation_log', 'input_tokens', '输入 token 数'),
            ('ma_invocation_log', 'output_tokens', '输出 token 数'),
            ('ma_invocation_log', 'total_cost', '总成本'),
            ('ma_invocation_log', 'error_code', '错误编码'),
            ('ma_invocation_log', 'error_message', '错误摘要'),
            ('ma_invocation_log', 'latency_ms', '耗时，单位毫秒'),
            ('ma_invocation_log', 'actor_service', '操作服务标识'),
            ('ma_invocation_log', 'delegated_user_id', '代理用户 ID'),
            ('ma_invocation_log', 'created_at', '创建时间'),
            ('ma_invocation_log', 'sensitivity_level', '敏感级别'),
            ('ma_invocation_log', 'created_by', '创建人'),
            ('ma_invocation_log', 'version', '版本号或乐观锁版本'),
            ('ma_invocation_log', 'routing_rule_name', '路由规则名称'),
            ('ma_invocation_log', 'routing_group', '路由分组'),
            ('ma_invocation_log', 'model_capability', '模型能力'),
            ('ma_model_provider', 'id', '主键 ID'),
            ('ma_model_provider', 'name', '名称'),
            ('ma_model_provider', 'provider_type', '供应商类型'),
            ('ma_model_provider', 'base_url', '基础地址'),
            ('ma_model_provider', 'api_key_ref', 'API Key 密钥引用'),
            ('ma_model_provider', 'status', '业务状态'),
            ('ma_model_provider', 'priority', '优先级'),
            ('ma_model_provider', 'timeout_ms', '超时时间，单位毫秒'),
            ('ma_model_provider', 'input_cost_per_1k_tokens', '每千输入 token 成本'),
            ('ma_model_provider', 'output_cost_per_1k_tokens', '每千输出 token 成本'),
            ('ma_model_provider', 'created_at', '创建时间'),
            ('ma_model_provider', 'updated_at', '最近更新时间'),
            ('ma_model_provider', 'created_by', '创建人'),
            ('ma_model_provider', 'updated_by', '更新人'),
            ('ma_model_provider', 'deleted_by', '删除人'),
            ('ma_model_provider', 'deleted_at', '删除时间'),
            ('ma_model_provider', 'version', '版本号或乐观锁版本'),
            ('ma_model_provider', 'routing_group', '路由分组'),
            ('ma_model_provider', 'capabilities', '能力列表'),
            ('ma_prompt_template', 'id', '主键 ID'),
            ('ma_prompt_template', 'prompt_key', 'Prompt 模板标识'),
            ('ma_prompt_template', 'name', '名称'),
            ('ma_prompt_template', 'version', '版本号或乐观锁版本'),
            ('ma_prompt_template', 'content', '正文内容'),
            ('ma_prompt_template', 'status', '业务状态'),
            ('ma_prompt_template', 'change_note', '变更说明'),
            ('ma_prompt_template', 'created_at', '创建时间'),
            ('ma_prompt_template', 'updated_at', '最近更新时间'),
            ('ma_prompt_template', 'created_by', '创建人'),
            ('ma_prompt_template', 'updated_by', '更新人'),
            ('ma_prompt_template', 'deleted_by', '删除人'),
            ('ma_prompt_template', 'deleted_at', '删除时间'),
            ('ma_prompt_template', 'high_risk', '是否高风险变更'),
            ('ma_prompt_template', 'approval_status', '审批状态'),
            ('ma_prompt_template', 'approved_by', '审批人'),
            ('ma_prompt_template', 'approved_at', '审批时间'),
            ('ma_prompt_template', 'approval_note', '审批说明'),
            ('rbac_permission', 'id', '主键 ID'),
            ('rbac_permission', 'code', '业务编码'),
            ('rbac_permission', 'resource_type', '资源类型'),
            ('rbac_permission', 'action', '操作动作'),
            ('rbac_permission', 'scope_mask', '权限作用域掩码'),
            ('rbac_permission', 'description', '业务说明'),
            ('rbac_permission', 'status', '业务状态'),
            ('rbac_permission', 'created_at', '创建时间'),
            ('rbac_permission', 'updated_at', '最近更新时间'),
            ('rbac_role', 'id', '主键 ID'),
            ('rbac_role', 'code', '业务编码'),
            ('rbac_role', 'name', '名称'),
            ('rbac_role', 'scope_type', '作用域类型'),
            ('rbac_role', 'is_system', '是否系统角色'),
            ('rbac_role', 'is_builtin', '是否内置角色'),
            ('rbac_role', 'status', '业务状态'),
            ('rbac_role', 'description', '业务说明'),
            ('rbac_role', 'created_by', '创建人'),
            ('rbac_role', 'created_at', '创建时间'),
            ('rbac_role', 'updated_by', '更新人'),
            ('rbac_role', 'updated_at', '最近更新时间'),
            ('rbac_role', 'deleted_by', '删除人'),
            ('rbac_role', 'deleted_at', '删除时间'),
            ('rbac_role', 'version', '版本号或乐观锁版本'),
            ('rbac_role_binding', 'id', '主键 ID'),
            ('rbac_role_binding', 'subject_type', '授权主体类型'),
            ('rbac_role_binding', 'subject_id', '授权主体 ID'),
            ('rbac_role_binding', 'role_id', '角色 ID'),
            ('rbac_role_binding', 'role_code', '角色编码'),
            ('rbac_role_binding', 'scope_type', '作用域类型'),
            ('rbac_role_binding', 'scope_id', '作用域 ID'),
            ('rbac_role_binding', 'condition_json', '授权条件 JSON'),
            ('rbac_role_binding', 'expires_at', '过期时间'),
            ('rbac_role_binding', 'status', '业务状态'),
            ('rbac_role_binding', 'created_by', '创建人'),
            ('rbac_role_binding', 'created_at', '创建时间'),
            ('rbac_role_binding', 'updated_by', '更新人'),
            ('rbac_role_binding', 'updated_at', '最近更新时间'),
            ('rbac_role_binding', 'deleted_by', '删除人'),
            ('rbac_role_binding', 'deleted_at', '删除时间'),
            ('rbac_role_binding', 'version', '版本号或乐观锁版本'),
            ('rbac_role_permission', 'id', '主键 ID'),
            ('rbac_role_permission', 'role_id', '角色 ID'),
            ('rbac_role_permission', 'permission_id', '权限 ID'),
            ('rbac_role_permission', 'effect', '授权效果'),
            ('rbac_role_permission', 'created_by', '创建人'),
            ('rbac_role_permission', 'created_at', '创建时间'),
            ('rbac_role_permission', 'deleted_by', '删除人'),
            ('rbac_role_permission', 'deleted_at', '删除时间'),
            ('rbac_role_permission', 'version', '版本号或乐观锁版本'),
            ('secret_local_store', 'id', '主键 ID'),
            ('secret_local_store', 'secret_ref_id', '密钥引用 ID'),
            ('secret_local_store', 'cipher_text', '密文'),
            ('secret_local_store', 'iv', '加密 IV'),
            ('secret_local_store', 'auth_tag', '认证标签'),
            ('secret_local_store', 'algorithm', '加密算法'),
            ('secret_local_store', 'master_key_version', '主密钥版本'),
            ('secret_local_store', 'status', '业务状态'),
            ('secret_local_store', 'created_by', '创建人'),
            ('secret_local_store', 'created_at', '创建时间'),
            ('secret_local_store', 'updated_by', '更新人'),
            ('secret_local_store', 'updated_at', '最近更新时间'),
            ('secret_local_store', 'deleted_by', '删除人'),
            ('secret_local_store', 'deleted_at', '删除时间'),
            ('secret_local_store', 'version', '版本号或乐观锁版本'),
            ('secret_provider', 'id', '主键 ID'),
            ('secret_provider', 'provider_code', '供应商编码'),
            ('secret_provider', 'provider_type', '供应商类型'),
            ('secret_provider', 'config_json', '供应商非敏感配置 JSON'),
            ('secret_provider', 'is_default', '是否默认供应商'),
            ('secret_provider', 'status', '业务状态'),
            ('secret_provider', 'created_by', '创建人'),
            ('secret_provider', 'created_at', '创建时间'),
            ('secret_provider', 'updated_by', '更新人'),
            ('secret_provider', 'updated_at', '最近更新时间'),
            ('secret_provider', 'deleted_by', '删除人'),
            ('secret_provider', 'deleted_at', '删除时间'),
            ('secret_provider', 'version', '版本号或乐观锁版本'),
            ('secret_reference', 'id', '主键 ID'),
            ('secret_reference', 'provider_id', '供应商 ID'),
            ('secret_reference', 'secret_ref', '密钥引用'),
            ('secret_reference', 'scope_type', '作用域类型'),
            ('secret_reference', 'scope_id', '作用域 ID'),
            ('secret_reference', 'purpose', '密钥用途'),
            ('secret_reference', 'masked_value', '脱敏展示值'),
            ('secret_reference', 'secret_version', '密钥版本'),
            ('secret_reference', 'status', '业务状态'),
            ('secret_reference', 'rotated_at', '最近轮换时间'),
            ('secret_reference', 'expires_at', '过期时间'),
            ('secret_reference', 'created_by', '创建人'),
            ('secret_reference', 'created_at', '创建时间'),
            ('secret_reference', 'updated_by', '更新人'),
            ('secret_reference', 'updated_at', '最近更新时间'),
            ('secret_reference', 'deleted_by', '删除人'),
            ('secret_reference', 'deleted_at', '删除时间'),
            ('secret_reference', 'version', '版本号或乐观锁版本'),
            ('test_design_candidate', 'id', '主键 ID'),
            ('test_design_candidate', 'task_id', '任务 ID'),
            ('test_design_candidate', 'project_id', '所属项目 ID，用于权限 scope、筛选和数据隔离'),
            ('test_design_candidate', 'requirement_id', '需求 ID'),
            ('test_design_candidate', 'api_id', 'API 资产 ID'),
            ('test_design_candidate', 'title', '标题'),
            ('test_design_candidate', 'description', '业务说明'),
            ('test_design_candidate', 'coverage_type', '覆盖类型'),
            ('test_design_candidate', 'priority', '优先级'),
            ('test_design_candidate', 'status', '业务状态'),
            ('test_design_candidate', 'preconditions', '前置条件'),
            ('test_design_candidate', 'steps_json', '测试步骤 JSON'),
            ('test_design_candidate', 'expected_result', '预期结果'),
            ('test_design_candidate', 'tags', '标签'),
            ('test_design_candidate', 'duplicate_key', '去重键'),
            ('test_design_candidate', 'confidence', '置信度'),
            ('test_design_candidate', 'prompt_key', 'Prompt 模板标识'),
            ('test_design_candidate', 'prompt_version', 'Prompt 模板版本'),
            ('test_design_candidate', 'model_invocation_id', '模型调用记录 ID'),
            ('test_design_candidate', 'model_provider_name', '模型供应商名称'),
            ('test_design_candidate', 'model_name', '模型名称'),
            ('test_design_candidate', 'asset_case_id', '测试用例资产 ID'),
            ('test_design_candidate', 'review_comment', '评审意见'),
            ('test_design_candidate', 'rejected_reason', '驳回原因'),
            ('test_design_candidate', 'ignored_reason', '忽略原因'),
            ('test_design_candidate', 'error_message', '错误摘要'),
            ('test_design_candidate', 'confirmed_by', '确认人'),
            ('test_design_candidate', 'confirmed_at', '确认时间'),
            ('test_design_candidate', 'version', '版本号或乐观锁版本'),
            ('test_design_candidate', 'created_at', '创建时间'),
            ('test_design_candidate', 'updated_at', '最近更新时间'),
            ('test_design_publish_record', 'id', '主键 ID'),
            ('test_design_publish_record', 'task_id', '任务 ID'),
            ('test_design_publish_record', 'candidate_id', '候选 ID'),
            ('test_design_publish_record', 'project_id', '所属项目 ID，用于权限 scope、筛选和数据隔离'),
            ('test_design_publish_record', 'requirement_id', '需求 ID'),
            ('test_design_publish_record', 'asset_case_id', '测试用例资产 ID'),
            ('test_design_publish_record', 'dry_run', '是否预发布检查'),
            ('test_design_publish_record', 'action', '操作动作'),
            ('test_design_publish_record', 'result', '处理结果'),
            ('test_design_publish_record', 'error_message', '错误摘要'),
            ('test_design_publish_record', 'published_by', '发布人'),
            ('test_design_publish_record', 'created_at', '创建时间'),
            ('test_design_review_record', 'id', '主键 ID'),
            ('test_design_review_record', 'candidate_id', '候选 ID'),
            ('test_design_review_record', 'task_id', '任务 ID'),
            ('test_design_review_record', 'project_id', '所属项目 ID，用于权限 scope、筛选和数据隔离'),
            ('test_design_review_record', 'action', '操作动作'),
            ('test_design_review_record', 'before_status', '操作前状态'),
            ('test_design_review_record', 'after_status', '操作后状态'),
            ('test_design_review_record', 'reviewer', '评审人'),
            ('test_design_review_record', 'comment', '评审说明'),
            ('test_design_review_record', 'diff_json', '字段差异 JSON'),
            ('test_design_review_record', 'created_at', '创建时间'),
            ('test_design_task', 'id', '主键 ID'),
            ('test_design_task', 'project_id', '所属项目 ID，用于权限 scope、筛选和数据隔离'),
            ('test_design_task', 'title', '标题'),
            ('test_design_task', 'status', '业务状态'),
            ('test_design_task', 'requirement_ids', '覆盖需求 ID 列表'),
            ('test_design_task', 'coverage_types', '覆盖类型列表'),
            ('test_design_task', 'prompt_key', 'Prompt 模板标识'),
            ('test_design_task', 'prompt_version', 'Prompt 模板版本'),
            ('test_design_task', 'model_invocation_id', '模型调用记录 ID'),
            ('test_design_task', 'model_provider_name', '模型供应商名称'),
            ('test_design_task', 'model_name', '模型名称'),
            ('test_design_task', 'total_requirements', '覆盖需求总数'),
            ('test_design_task', 'generated_count', '已生成候选数量'),
            ('test_design_task', 'confirmed_count', '已确认候选数量'),
            ('test_design_task', 'published_count', '已发布候选数量'),
            ('test_design_task', 'error_message', '错误摘要'),
            ('test_design_task', 'requested_by', '请求发起人'),
            ('test_design_task', 'created_at', '创建时间'),
            ('test_design_task', 'updated_at', '最近更新时间'),
            ('test_design_task', 'idempotency_key', '幂等键'),
            ('test_design_task', 'request_digest', '请求摘要'),
            ('test_design_task', 'input_digest', '输入摘要'),
            ('test_design_task', 'context_summary_json', '脱敏上下文摘要 JSON')
        ) as comments(table_name, column_name, description)
    loop
        if exists (
            select 1 from information_schema.columns
            where table_schema = current_schema()
              and table_name = item.table_name
              and column_name = item.column_name
        ) then
            execute format('comment on column %I.%I is %L', item.table_name, item.column_name, item.description);
        end if;
    end loop;
end $$;
